---
  
- hosts: 
    - wordpress-servers
  user: root
  gather_facts: False

  tasks:
  - include_vars: group_vars/all

  - name: Pull latest code for all wordpress sites
    git: repo={{ item.repository }} dest=/srv/{{ item.project_name }}/ accept_hostkey=yes force=yes
    with_items: sites

  - name: Change ownership of WordPress directories to www-data
    file: path=/srv/{{ item.project_name }}/ owner=ubuntu group=www-data mode=0755 state=directory recurse=yes
    with_items: sites

  - name: Restart php5-fpm Service
    service: name=php5-fpm state=restarted enabled=yes
